site_name: PS2 Homebrew Wiki
site_url: https://ps2hackswiki.netlify.app
docs_dir: docs/
theme:
  name: 'material'
  features:
    - navigation.sections

nav:
  - Home: index.md
  - Hardware:
    - Controller adapters: hardware/controller-adapters.md
  - Software:
    - Create drive partitions: software/create-drive-partitions.md
    - HDL Batch Installer: software/hdl-batch-installer.md
    - Install FreeHDBoot: software/install-freehdboot.md
    - OPL: software/OPL.md
    - Add artwork to OPL: software/add-artwork-to-opl.md
