site_name: PS2 Hacks Wiki
site_url: https://ps2hackswiki.netlify.app
docs_dir: docs/
theme:
  name: 'material'
  logo: assets/controller.png
  favicon: assets/controller.png
  features:
    - navigation.sections
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home:
    - index.md
  - Hardware:
    - hardware/index.md
    - Burn discs with ESR: hardware/burn-discs-esr.md
    - Controller adapters: hardware/controller-adapters.md
  - Software:
    - software/index.md
    - Internal HDD guide: software/internal-hdd-guide.md
    - Create drive partitions: software/create-drive-partitions.md
    - Install OPL: software/install-OPL.md
    - HDL Batch Installer: software/hdl-batch-installer.md
    - Add artwork to OPL: software/add-artwork-to-opl.md
    - OPL guide: software/OPL-guide.md
    - Install FreeHDBoot: software/install-freehdboot.md
